on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: echo "Running linter (dummy)"

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running tests (dummy)"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: echo "Building project (dummy)"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploying to production (dummy)"