name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        run: echo "Running linter"

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
        run: echo "Running tests (dummy)"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: echo "Building project"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        run: echo "Deploying to production"